TMP_PROJECT_PATH=D:\\Workspace\\uncaught exception\\data\\temp_project
EXPERIMENT_INTERMEDIATE_PROCESS_DATA_PATH=D:\\Workspace\\uncaught exception\\data\\experiment_detail
REPOSITORY_INDEX_FILE=D:\\Workspace\\uncaught exception\\data\\collected_repos(1670).json
REPOSITORY_DATA_PATH=D:\\Top1670JavaProjects
EXPERIMENT_MARK=ETEST
EXPERIMENT_SOURCE=D:\\Workspace\\uncaught exception\\data\\experiment_result_cleanE0502.json
EXPERIMENT_TARGET=D:\\Workspace\\uncaught exception\\data\\experiment_resultE0000.json
LLM_API_KEY=bce-v3/ALTAK-sdd15T2SrcIYEjww4fKtZ/2871bf14e0a87a37f7df3c4275db0b9b2370dc3f
LLM_API_URL=https://qianfan.baidubce.com/v2/chat/completions
LLM_MODEL_NAME=ernie-4.5-turbo-32k
GITHUB_USERNAME=orange-78
GITHUB_TOKEN=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